### ISSUE TITLE
a new syntex_syntax release for crates.io?

### ISSUE THREAD

**Issue by phildawes** [serde-rs/syntex#1]
Hi @erickt. 
My https://github.com/phildawes/racer project depends on libsyntax, and Steve Klabnik pointed me to your syntex project as a way to get racer working with rust beta2 (and the upcoming 1.0 release). 
Unfortunately racer depends on features in libsyntax that aren't in the syntex 0.1.0 crate from crates.io. Are you planning another release before 1.0?

Thanks v much!

-Phil

**Comment by erickt** [comment]
Hi @phildawes! I've just uploaded version [0.3.0](https://crates.io/crates/syntex_syntax) to crates.io. Unfortunately it still requires nightly to compile. I've created https://github.com/rust-lang/rust/issues/24518, which tracks making the upstream libsyntax compile on stable, which then I can pull into syntex.
