### ISSUE TITLE
Parser::parse_item_nopanic panics

### ISSUE THREAD

**Issue by johannhof** [serde-rs/syntex#18]
To further improve string parsing in `rustmft`, I want to be able to skip parse errors on single items and use `Parser::parse_item_nopanic`. 

Despite the name, that function does, however, indeed panic because `Parser::parse_outer_attributes`, which is called by `Parser::parse_item_nopanic` includes panicking code.

Code context: https://github.com/serde-rs/syntex/blob/master/syntex_syntax/src/parse/parser.rs#L5613

**Comment by dtolnay** [comment]
Looks like this function no longer exists in rustc.
