### ISSUE TITLE
Needs to be updated for nightly >= 2015-12-05

### ISSUE THREAD

**Issue by sgrif** [serde-rs/syntex#24]
https://github.com/rust-lang/rust/pull/29850 caused breaking changes that need to be accounted for here.  I'd submit a PR, but I'm not sure what's required or if there's an automated way you normally pull in changes from upstream. I'm also unsure if any additional work needs to be done since this legitimately changes language semantics in some places. (Perhaps a CONTRIBUTING.md file, or a section in the README can be added for other people looking to fix issues in the future?)

**Comment by erickt** [comment]
Just updated to sync with rust. It's not particularly automated, but I did write up the process in [RELEASE-PROCESS.md](https://github.com/serde-rs/syntex/blob/master/RELEASE-PROCESS.md) :)
