### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by calebmer** [serde-rs/syntex#35]
Is it possible to make a cli for `syntex`? I like the project, but our entire build system uses `Makefile`s and not the `build.rs`. In addition some of us have a subjective dislike of `build.rs` as a build tool.

**Comment by erickt** [comment]
@calebmer: No it shouldn't be too hard. I'm working on a Rust RFC to improve the Rust's code generation support. I didn't talk about non-cargo support, so I'll make sure to take this into consideration. Is your project online? I'm sure the cargo folks would be interested to hear your feedback on what you don't like about the approach.

**Comment by calebmer** [comment]
Yes, the project is on [GitHub](https://github.com/ardite/ardite-core) and I'd love to give feedback. Is there a link to the RFC/appropriate places?

**Comment by dtolnay** [comment]
I don't think we should encourage this. This prevents Cargo from being able to distribute your crate. If there is specific actionable feedback about shortcomings of the build.rs approach then we should fix those in Cargo.

If you really need a Syntex cli, the build script **_is**_ one. Rename build.rs to main.rs and `cargo install` it.
