### ISSUE TITLE
Minimum version of Rust supported

### ISSUE THREAD

**Issue by benashford** [serde-rs/syntex#36]
I notice from the `.travis.yml` file that this project is tested against: 1.5.0, stable, beta and nightly (although not 1.6.0).

Does this mean 1.5.0 is the minimum target?  Is there a policy on this?

I ask because, given that the parent `libsyntax` is unstable and frequently changing, the work required to integrate change with this library gets harder the more versions of Rust supported.  Indeed there is code for compatibility included in Syntex for Rust 1.5.0 that is unnecessary with the latest stable Rusts, e.g. `min_by_key` in `src/util/lev_distance.rs`

**Comment by erickt** [comment]
There's no policy yet, it's more that someone asked me to support 1.5.0. It's typically not _that_ hard to maintain backwards compatibility. At worst it might take an hour or so to rewrite the code to be backwards compatible. We can always apply pressure to the upstream libsyntax project to not diverge that much from being able to run on older versions of Rust too.

Is there a particular version of Rust you need Syntex to work against?

**Comment by benashford** [comment]
No, there's no particular version of Rust I need.  Not beyond the usual range: nightly, beta, stable, etc., I don't have any particular backward compatibility requirements.  

I was looking at Syntex and the other components that make up Serde after a recent `libsyntax` change broke compatibility and was just wondering if there were any rules for the project.

Thank you.
