### ISSUE TITLE
Panic when passing a generic type to a macro

### ISSUE THREAD

**Issue by jmgao** [serde-rs/syntex#40]
When running rustfmt on code that passes a generic type into a macro, I'm seeing the [following panic](https://github.com/serde-rs/syntex/blob/master/syntex_syntax/src/errors/mod.rs#L360):
`thread '<main>' panicked at 'explicit panic', [<snip>/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/errors/mod.rs:360]`

Here's a roughly minified test case:

```
macro_rules! test {
  ($t: ty) => {
    fn test(_: $t) -> i32 {
      1
    }
  }
}

test!(Vec<u8>);

fn main() {
  std::process::exit(test(Vec::new()));
}
```

**Comment by dtolnay** [comment]
I was able to reproduce this using rustfmt 0.4.0 but not rustfmt 0.4.1 so the bug has been fixed. Interestingly those both use the same version of Syntex: 0.30.0.
