### ISSUE TITLE
Create an Item from an inner attribute

### ISSUE THREAD

**Issue by Yamakaky** [serde-rs/syntex#46]
My goal is to have an attribute `#![allow(non_camel_case_types)]` in a generated Mod. I tried to use `ExtCtxt::item`, but it requires a `ItemKind`, and non of it's variants correspond. Is it a bug?

**Comment by Manishearth** [comment]
Inner attributes are just attributes on the mod (they are not items). If you generated the mod you can attach attributes yourself.

I'm not quite sure what the larger situation here is.

**Comment by Yamakaky** [comment]
I work on bindgen https://github.com/crabtw/rust-bindgen/blob/master/src/gen.rs#L179.

**Comment by Yamakaky** [comment]
Mod only contains Items and a span

**Comment by Manishearth** [comment]
Where are you creating the `Mod` itself? Inner attributes are a field on the `Mod`, not contents.

**Comment by Manishearth** [comment]
The mod itself is an item, you need to generate an `Item` with an `ItemKind::Mod` with attribute on it

**Comment by Manishearth** [comment]
(closing, this isn't related to syntex, you may want to ask further questions on #rust-internals on Mozilla IRC)

**Comment by Yamakaky** [comment]
Ok, sorry.
