### ISSUE TITLE
`#cfg(test)` is ignored even if `cargo test` is used

### ISSUE THREAD

**Issue by Byron** [serde-rs/syntex#9]
Even though integration tests with `syntex` might be difficult to achive as they are a separate program which needs its own `build.rs` program configuration, standard unit-tests should work out of the box as they are included if `cargo test` is run on the crate in question.

For some reason, items with `#[cfg(test)]` meta-data are ignored by `syntex`, which makes unit-testing impossible as these items are stripped in the generated output file.

I am not sure why this is, and how it is possible to tell syntex that tests should be part of the output.
A working workaround is to simply not use conditional compilation on test items.

Nonetheless, I would be glad if there would be some hint on how to use standard workflows when `syntex` is involved, which might also include integration testing (i.e. .rs files within the `tests` subdirectory).

**Comment by erickt** [comment]
Should be fixed now :)

**Comment by Byron** [comment]
Thank you ! Tests do show up now.
